version: "3.7"
services:
  database:
    container_name: "pgdb"
    image: postgres
    profiles:
      - postgres
    restart: always
    environment:
      - POSTGRES_USER=darika
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tracks_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: "myserver"
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6565:6565"
    restart: unless-stopped
    tty: true
    depends_on:
      - database
  client:
    container_name: "myclient"
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "7575:7575"
#      - "8080:8080"
    restart: unless-stopped
    tty: true
    depends_on:
      - database
      - myserver
